In [2]:
# Import Numpy library
import numpy as np

# Numpy Array Creation

In [3]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [4]:
# Display the type of an object
type(list1)

list

In [5]:
# Convert List to Numpy Array
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [6]:
# Memory address of an array object
arr1.data

In [7]:
# Display type of an object
type(arr1)

numpy.ndarray

In [8]:
# Datatype of array
arr1.dtype

dtype('int64')

In [9]:
# Convert Integer Array to Float
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
# Generate evenly spaced numbers (space = 1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Genrate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
# Genrate numbers between 10 to 100 with a space of 10 descending order
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [13]:
# Shape of array
arr3 = np.arange(0,10)
print(arr3.shape)
print(arr3)

(10,)
[0 1 2 3 4 5 6 7 8 9]


In [14]:
# Size of array
arr3.size

10

In [15]:
# Dimension
arr3.ndim

1

In [16]:
# Datatype of object
arr3.dtype

dtype('int64')

In [17]:
# Bytes comsumed by one element of an array object
arr3.itemsize

8

In [18]:
# Length of array
len(arr3)

10

In [19]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# Generate an array of ones with given shape
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# Repeat 10 five times in an array
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [23]:
# Repeat each element in array 'a' thrice
a = np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [24]:
# Array of 10's
np.full(5,10)

array([10, 10, 10, 10, 10])

In [25]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ar1[ar1%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
# Generate array of even numbers

ar1 = np.arange(1,20)
ar1[ar1%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# Generate evenly spaced 4 numbers between 10 to 20
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [28]:
# Create an array of random values
np.random.random(4)

array([0.11673987, 0.78415614, 0.36936833, 0.92406852])

In [33]:
# Generate an array of Random Integer numbers
print(np.random.randint(0, 500, 5))
print(np.random.randint(0, 500, 10))


[233 147 467 257  57]
[214 251  31 455 119 355 408  58 295 105]


In [35]:
# Using random.seed we can generate same number of Random numbers

np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [36]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10, size=(10))
f1

array([6.96058759, 6.71589008, 8.64524854, 7.19286122, 5.29838948,
       6.99022128, 8.68997703, 5.91245865, 5.87725878, 7.65775687])

In [37]:
# Extract Integer part
np.floor(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [38]:
# Truncate decimal part
np.trunc(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [39]:
# Convert Float Array to Integer array
f1.astype(int)


array([6, 6, 8, 7, 5, 6, 8, 5, 5, 7])

In [41]:
# Normal distribution (mean=0 and variance=1)

b2 = np.random.randn(10)
b2

array([-0.74856868,  0.24036728, -1.85563747, -1.7794548 , -2.75022426,
       -0.23415755, -0.69598118, -1.77413406,  2.36160126,  0.03499308])

In [42]:
arr1

array([10, 20, 30, 40, 50, 60])

In [43]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(arr1):
  print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


# Operations on an Array